<?php
require_once '../config/db.php';

$username = 'admin';
$password = 'password123';
$hashed = password_hash($password, PASSWORD_DEFAULT);

try {
    // Delete existing admin
    $pdo->prepare("DELETE FROM admin WHERE username = ?")->execute([$username]);
    
    // Insert new admin with fresh hash generated by your current PHP engine
    $stmt = $pdo->prepare("INSERT INTO admin (username, password) VALUES (?, ?)");
    $stmt->execute([$username, $hashed]);

    echo "<h2 style='color: green; font-family: sans-serif;'> Admin account reset successfully!</h2>";
    echo "<p style='font-family: sans-serif;'><strong>Username:</strong> admin<br><strong>Password:</strong> password123</p>";
    echo "<p><a href='login.php' style='display: inline-block; padding: 10px 16px; background: black; color: white; text-decoration: none; border-radius: 6px;'>Go to Admin Login &rarr;</a></p>";
} catch (Exception $e) {
    echo "<h2 style='color: red;'>Error: " . $e->getMessage() . "</h2>";
}